/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsOttRouteImport } from './routes/products.ott'
import { Route as ProductsCommerceRouteImport } from './routes/products.commerce'
import { Route as ProductsCdnRouteImport } from './routes/products.cdn'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsOttRoute = ProductsOttRouteImport.update({
  id: '/products/ott',
  path: '/products/ott',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCommerceRoute = ProductsCommerceRouteImport.update({
  id: '/products/commerce',
  path: '/products/commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCdnRoute = ProductsCdnRouteImport.update({
  id: '/products/cdn',
  path: '/products/cdn',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/cdn': typeof ProductsCdnRoute
  '/products/commerce': typeof ProductsCommerceRoute
  '/products/ott': typeof ProductsOttRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/cdn': typeof ProductsCdnRoute
  '/products/commerce': typeof ProductsCommerceRoute
  '/products/ott': typeof ProductsOttRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/cdn': typeof ProductsCdnRoute
  '/products/commerce': typeof ProductsCommerceRoute
  '/products/ott': typeof ProductsOttRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/careers'
    | '/company'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/privacy'
    | '/solutions'
    | '/status'
    | '/terms'
    | '/products/$slug'
    | '/products/cdn'
    | '/products/commerce'
    | '/products/ott'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/careers'
    | '/company'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/privacy'
    | '/solutions'
    | '/status'
    | '/terms'
    | '/products/$slug'
    | '/products/cdn'
    | '/products/commerce'
    | '/products/ott'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/careers'
    | '/company'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/privacy'
    | '/solutions'
    | '/status'
    | '/terms'
    | '/products/$slug'
    | '/products/cdn'
    | '/products/commerce'
    | '/products/ott'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRoute
  PrivacyRoute: typeof PrivacyRoute
  SolutionsRoute: typeof SolutionsRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsCdnRoute: typeof ProductsCdnRoute
  ProductsCommerceRoute: typeof ProductsCommerceRoute
  ProductsOttRoute: typeof ProductsOttRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/ott': {
      id: '/products/ott'
      path: '/products/ott'
      fullPath: '/products/ott'
      preLoaderRoute: typeof ProductsOttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/commerce': {
      id: '/products/commerce'
      path: '/products/commerce'
      fullPath: '/products/commerce'
      preLoaderRoute: typeof ProductsCommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/cdn': {
      id: '/products/cdn'
      path: '/products/cdn'
      fullPath: '/products/cdn'
      preLoaderRoute: typeof ProductsCdnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRoute,
  PrivacyRoute: PrivacyRoute,
  SolutionsRoute: SolutionsRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsCdnRoute: ProductsCdnRoute,
  ProductsCommerceRoute: ProductsCommerceRoute,
  ProductsOttRoute: ProductsOttRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
